openapi: 3.0.3

info:
  title: Здоровый сон
  version: 1.0.0
  contact: {}
servers:
  - url: https://api.healthysleep.sixhands.co
  - url: https://api.healthysleep.sixhands.co}
paths:
  /profile/:
    get:
      tags:
        - Общие запросы
      summary: Профиль
      description: Профиль
      operationId: ''
      responses:
        '200':
          description: ''
  /auth/login/:
    post:
      tags:
        - Общие запросы
      summary: Запрос токена
      description: Запрос токена
      operationId: '1'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@mail.com
                password:
                  type: string
                  example: '123456'
            examples:
              Запрос токена:
                value:
                  email: user@mail.com
                  password: '123456'
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: doctor@test.ru
                password:
                  type: string
                  example: 12345678aA!
      responses:
        '200':
          description: ''
      security:
        - basicAuth: []
  /auth/refresh:
    post:
      tags:
        - Общие запросы
      summary: Обновление токена
      description: Обновление токена
      operationId: '2'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: refresh_token
            examples:
              Обновление токена:
                value:
                  refreshToken: refresh_token
      responses:
        '200':
          description: ''
  /auth/reset_password/:
    post:
      tags:
        - Общие запросы
      summary: Восстановление пароля
      description: Восстановление пароля
      operationId: '3'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: bla-bla@gmail.com
            examples:
              Восстановление пароля:
                value:
                  email: bla-bla@gmail.com
      responses:
        '200':
          description: ''
  /profile/change_password/:
    patch:
      tags:
        - Общие запросы
      summary: Смена пароля
      description: Смена пароля
      operationId: '4'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                NewPassword:
                  type: string
                  example: '12321'
                Password:
                  type: string
                  example: '123'
            examples:
              Смена пароля:
                value:
                  NewPassword: '12321'
                  Password: '123'
      responses:
        '200':
          description: ''
  /auth/new:
    post:
      tags:
        - Admin
      summary: Создание нового пользователя
      description: Создание нового пользователя
      operationId: '5'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Additional:
                  type: string
                  example: string
                Birthdate:
                  type: string
                  example: datetime
                Email:
                  type: string
                  example: string
                Fathername:
                  type: string
                  example: string
                ID:
                  type: number
                  example: 35
                Model:
                  type: string
                  example: string
                Name:
                  type: string
                  example: string
                Password:
                  type: string
                  example: string
                PhoneNumber:
                  type: string
                  example: string
                Surname:
                  type: string
                  example: string
            examples:
              Создание нового пользователя:
                value:
                  Additional: string
                  Birthdate: datetime
                  Email: string
                  Fathername: string
                  ID: 35
                  Model: string
                  Name: string
                  Password: string
                  PhoneNumber: string
                  Surname: string
      responses:
        '200':
          description: ''
  /profile/{id}/:
    get:
      tags:
        - Admin
      summary: Просмотр информации о пользователе
      description: Просмотр информации о пользователе
      operationId: '7'
      responses:
        '200':
          description: ''
    delete:
      tags:
        - Admin
      summary: Удаление пользователя
      description: Удаление пользователя
      operationId: '6'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: ''
    patch:
      tags:
        - Admin
      summary: Обновление информации о пользователе
      description: Обновление информации о пользователе
      operationId: '8'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Fathername:
                  type: string
                  example: Евгеньевич
            examples:
              Обновление информации о пользователе:
                value: ''
      responses:
        '200':
          description: ''
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /admin/users:
    get:
      tags:
        - Admin
      summary: Получение списка пользователей
      description: Получение списка пользователей
      operationId: '9'
      parameters:
        - name: page
          in: query
          schema:
            type: string
            example: '1'
        - name: size
          in: query
          schema:
            type: string
            example: '20'
      responses:
        '200':
          description: ''
      security:
        - basicAuth: []
  /statistics/view/{PrivateID}/:
    get:
      tags:
        - User
      summary: Запрос статистики
      description: Запрос статистики
      operationId: '10'
      parameters:
        - name: From
          in: query
          schema:
            type: string
            example: '{}'
        - name: To
          in: query
          schema:
            type: string
            example: '{}'
      requestBody:
        content:
          application/json:
            examples:
              Запрос статистики:
                value: ''
      responses:
        '200':
          description: Статистика
          headers:
            Allow:
              schema:
                type: string
                example: GET, HEAD, OPTIONS
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Encoding:
              schema:
                type: string
                example: gzip
            Content-Language:
              schema:
                type: string
                example: ru
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
            Date:
              schema:
                type: string
                example: Fri, 10 Jan 2025 13:03:12 GMT
            Referrer-Policy:
              schema:
                type: string
                example: same-origin
            Server:
              schema:
                type: string
                example: nginx
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Vary:
              schema:
                type: string
                example: Accept, Accept-Language, origin
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              schema:
                type: string
                example: DENY
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        ahi:
                          type: number
                          example: 0
                        ai:
                          type: number
                          example: 0
                        cai:
                          type: number
                          example: 0
                        duration:
                          type: number
                          example: 10
                        epr:
                          type: number
                          example: 0
                        hi:
                          type: number
                          example: 0
                        leak:
                          type: number
                          example: 10
                        mask_pressure:
                          type: number
                          example: 0
                        max_pressure:
                          type: number
                          example: 5
                        min_pressure:
                          type: number
                          example: 4
                        oai:
                          type: number
                          example: 0
                        ramp_time:
                          type: number
                          example: 0
                        temperature:
                          type: number
                          example: 0
                        uai:
                          type: number
                          example: 0
                    date:
                      type: string
                      example: '2024-09-26'
                    id:
                      type: number
                      example: 1148
                    user:
                      type: number
                      example: 62
                example:
                  - data:
                      ahi: 0
                      ai: 0
                      cai: 0
                      duration: 10
                      epr: 0
                      hi: 0
                      leak: 10
                      mask_pressure: 0
                      max_pressure: 5
                      min_pressure: 4
                      oai: 0
                      ramp_time: 0
                      temperature: 0
                      uai: 0
                    date: '2024-09-26'
                    id: 1148
                    user: 62
                  - data:
                      ahi: 6.58
                      ai: 0
                      cai: 0
                      duration: 63
                      epr: 0
                      hi: 6.58
                      leak: 5
                      mask_pressure: 0
                      max_pressure: 5
                      min_pressure: 5
                      oai: 0
                      ramp_time: 0
                      temperature: 0
                      uai: 0
                    date: '2024-10-07'
                    id: 1147
                    user: 62
                  - data:
                      ahi: 0
                      ai: 0
                      cai: 0
                      duration: 2
                      epr: 0
                      hi: 0
                      leak: 2
                      mask_pressure: 0
                      max_pressure: 6
                      min_pressure: 5
                      oai: 0
                      ramp_time: 0
                      temperature: 0
                      uai: 0
                    date: '2024-10-08'
                    id: 1150
                    user: 62
                  - data:
                      ahi: 4.83
                      ai: 0
                      cai: 0
                      duration: 198
                      epr: 0
                      hi: 4.83
                      leak: 34
                      mask_pressure: 0
                      max_pressure: 6
                      min_pressure: 6
                      oai: 0
                      ramp_time: 0
                      temperature: 0
                      uai: 0
                    date: '2024-10-10'
                    id: 1146
                    user: 62
                  - data:
                      ahi: 2.11
                      ai: 0
                      cai: 0
                      duration: 313
                      epr: 0
                      hi: 2.11
                      leak: 22
                      mask_pressure: 0
                      max_pressure: 6
                      min_pressure: 6
                      oai: 0
                      ramp_time: 0
                      temperature: 0
                      uai: 0
                    date: '2024-10-11'
                    id: 1145
                    user: 62
                  - data:
                      ahi: 2.6
                      ai: 0.2
                      cai: 0
                      duration: 300
                      epr: 0
                      hi: 2.4
                      leak: 19
                      mask_pressure: 0
                      max_pressure: 6
                      min_pressure: 6
                      oai: 0
                      ramp_time: 0
                      temperature: 0
                      uai: 0
                    date: '2024-10-12'
                    id: 1149
                    user: 62
              examples:
                Статистика:
                  value:
                    - data:
                        ahi: 0
                        ai: 0
                        cai: 0
                        duration: 10
                        epr: 0
                        hi: 0
                        leak: 10
                        mask_pressure: 0
                        max_pressure: 5
                        min_pressure: 4
                        oai: 0
                        ramp_time: 0
                        temperature: 0
                        uai: 0
                      date: '2024-09-26'
                      id: 1148
                      user: 62
                    - data:
                        ahi: 6.58
                        ai: 0
                        cai: 0
                        duration: 63
                        epr: 0
                        hi: 6.58
                        leak: 5
                        mask_pressure: 0
                        max_pressure: 5
                        min_pressure: 5
                        oai: 0
                        ramp_time: 0
                        temperature: 0
                        uai: 0
                      date: '2024-10-07'
                      id: 1147
                      user: 62
                    - data:
                        ahi: 0
                        ai: 0
                        cai: 0
                        duration: 2
                        epr: 0
                        hi: 0
                        leak: 2
                        mask_pressure: 0
                        max_pressure: 6
                        min_pressure: 5
                        oai: 0
                        ramp_time: 0
                        temperature: 0
                        uai: 0
                      date: '2024-10-08'
                      id: 1150
                      user: 62
                    - data:
                        ahi: 4.83
                        ai: 0
                        cai: 0
                        duration: 198
                        epr: 0
                        hi: 4.83
                        leak: 34
                        mask_pressure: 0
                        max_pressure: 6
                        min_pressure: 6
                        oai: 0
                        ramp_time: 0
                        temperature: 0
                        uai: 0
                      date: '2024-10-10'
                      id: 1146
                      user: 62
                    - data:
                        ahi: 2.11
                        ai: 0
                        cai: 0
                        duration: 313
                        epr: 0
                        hi: 2.11
                        leak: 22
                        mask_pressure: 0
                        max_pressure: 6
                        min_pressure: 6
                        oai: 0
                        ramp_time: 0
                        temperature: 0
                        uai: 0
                      date: '2024-10-11'
                      id: 1145
                      user: 62
                    - data:
                        ahi: 2.6
                        ai: 0.2
                        cai: 0
                        duration: 300
                        epr: 0
                        hi: 2.4
                        leak: 19
                        mask_pressure: 0
                        max_pressure: 6
                        min_pressure: 6
                        oai: 0
                        ramp_time: 0
                        temperature: 0
                        uai: 0
                      date: '2024-10-12'
                      id: 1149
                      user: 62
    parameters:
      - name: PrivateID
        in: path
        required: true
        schema:
          type: string
  /statistics/upload/{id}:
    post:
      tags:
        - User
      summary: Загрузка статистики
      description: Загрузка статистики
      operationId: '11'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: ''
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /patientslink:
    post:
      tags:
        - Doctor
      summary: Привязка пациента
      description: Привязка пациента
      operationId: '18'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Doctor_ID:
                  type: number
                  example: 1
                patienst_ID:
                  type: number
                  example: 100
            examples:
              Привязка пациента:
                value:
                  Doctor_ID: 1
                  patienst_ID: 100
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
    delete:
      tags:
        - User
      summary: Отвязать врача от пациента
      description: Отвязать врача от пациента
      operationId: '12'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Doctor_ID:
                  type: number
                  example: 100
                Patient_ID:
                  type: number
                  example: 100
            examples:
              Отвязать врача от пациента:
                value: ''
      responses:
        '200':
          description: ''
  /patients:
    post:
      tags:
        - User
      summary: Регистрация
      description: Регистрация
      operationId: '13'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Additional:
                  type: string
                  example: Бла-бла
                Birthdate:
                  type: number
                  example: 202021
                Email:
                  type: string
                  example: Lev.clav@gmail.com
                Fathername:
                  type: string
                  example: Евгеньевич
                ID:
                  type: number
                  example: 35
                Model:
                  type: array
                  items:
                    type: string
                    example: ResMed
                  example:
                    - ResMed
                    - ResVent
                    - WTF
                Name:
                  type: string
                  example: Лев
                Password:
                  type: string
                  example: Password
                PhoneNumber:
                  type: string
                  example: '+79312014807'
                Surname:
                  type: string
                  example: Славутский
            examples:
              Регистрация:
                value:
                  Additional: Бла-бла
                  Birthdate: 202021
                  Email: Lev.clav@gmail.com
                  Fathername: Евгеньевич
                  ID: 35
                  Model:
                    - ResMed
                    - ResVent
                    - WTF
                  Name: Лев
                  Password: Password
                  PhoneNumber: '+79312014807'
                  Surname: Славутский
      responses:
        '200':
          description: ''
  /patients/data/upload:
    post:
      tags:
        - User
      summary: Данные пациента
      description: Данные пациента
      operationId: '14'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Data:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
  /data/{patientId}:
    get:
      tags:
        - Doctor
      summary: Девайсы
      description: Девайсы
      operationId: '15'
      parameters:
        - name: from=2024-03-01&to=2024-03-20
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
    parameters:
      - name: patientId
        in: path
        required: true
        schema:
          type: string
  /doctors/patients/:
    get:
      tags:
        - Doctor
      summary: Пациенты
      description: Пациенты
      operationId: '16'
      parameters:
        - name: page
          in: query
          schema:
            type: string
            example: '1'
        - name: size
          in: query
          schema:
            type: string
            example: '20'
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
  /doctors:
    post:
      tags:
        - Doctor
      summary: Регистрация
      description: Регистрация
      operationId: '17'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Birthdate:
                  type: number
                  example: 202021
                Email:
                  type: string
                  example: Lev.clav@gmail.com
                Fathername:
                  type: string
                  example: Евгеньевич
                ID:
                  type: number
                  example: 35
                Name:
                  type: string
                  example: Лев
                Password:
                  type: string
                  example: Password
                PhoneNumber:
                  type: string
                  example: '+79312014807'
                Surname:
                  type: string
                  example: Славутский
            examples:
              Регистрация:
                value:
                  Birthdate: 202021
                  Email: Lev.clav@gmail.com
                  Fathername: Евгеньевич
                  ID: 35
                  Name: Лев
                  Password: Password
                  PhoneNumber: '+79312014807'
                  Surname: Славутский
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Общие запросы
    description: >-
      Здесь находятся общие запросы, которые может выполнять каждая роль в
      системе
  - name: Admin
  - name: User
    description: >-
      Здесь находятся запросы, которые могут выполнять только пользователи со
      статусом "Пациент"
  - name: Doctor
